**Bag of Words**

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame({"text":["people watch dswithkunal",
                         "dswithkunal watch dswithkunal",
                         "people write comment",
                          "dswithkunal write comment"],"output":[1,1,0,0]})

df

text  output
0       people watch dswithkunal       1
1  dswithkunal watch dswithkunal       1
2           people write comment       0
3      dswithkunal write comment       0

In [3]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()

In [4]:
bow=cv.fit_transform(df['text'])

In [5]:
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'dswithkunal': 1, 'write': 4, 'comment': 0}


In [6]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())
print(bow[3].toarray())

[[0 1 1 1 0]]
[[0 2 0 1 0]]
[[1 0 1 0 1]]
[[1 1 0 0 1]]


In [7]:
cv.transform(['Kunal watch dswithkunal']).toarray()

array([[0, 1, 0, 1, 0]])

In [8]:
x=bow.toarray()
y=df['output']

In [9]:
x

array([[0, 1, 1, 1, 0],
       [0, 2, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [1, 1, 0, 0, 1]])

In [10]:
y

0    1
1    1
2    0
3    0
Name: output, dtype: int64

**N-Grams**

In [11]:
df

text  output
0       people watch dswithkunal       1
1  dswithkunal watch dswithkunal       1
2           people write comment       0
3      dswithkunal write comment       0

In [13]:
#bi grams
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(ngram_range=(2,2))

In [14]:
ngram=cv.fit_transform(df['text'])

In [15]:
print(cv.vocabulary_)

{'people watch': 2, 'watch dswithkunal': 4, 'dswithkunal watch': 0, 'people write': 3, 'write comment': 5, 'dswithkunal write': 1}


In [16]:
print(ngram[0].toarray())
print(ngram[1].toarray())
print(ngram[2].toarray())
print(ngram[3].toarray())

[[0 0 1 0 1 0]]
[[1 0 0 0 1 0]]
[[0 0 0 1 0 1]]
[[0 1 0 0 0 1]]


**TF-IDF(Term Frequency Inverse Document Frequency)**

In [17]:
df

text  output
0       people watch dswithkunal       1
1  dswithkunal watch dswithkunal       1
2           people write comment       0
3      dswithkunal write comment       0

In [18]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfid=TfidfVectorizer()

In [19]:
tfid.fit_transform(df['text']).toarray()

array([[0.        , 0.49681612, 0.61366674, 0.61366674, 0.        ],
       [0.        , 0.8508161 , 0.        , 0.52546357, 0.        ],
       [0.57735027, 0.        , 0.57735027, 0.        , 0.57735027],
       [0.61366674, 0.49681612, 0.        , 0.        , 0.61366674]])

In [20]:
print(tfid.idf_)

[1.51082562 1.22314355 1.51082562 1.51082562 1.51082562]
